// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: s3.proto

/*
Package s3 is a generated protocol buffer package.

It is generated from these files:
	s3.proto

It has these top-level messages:
	CHelloRequest
	CHelloResponse
*/
package s3

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for S3 service

type S3Service interface {
	CHello(ctx context.Context, in *CHelloRequest, opts ...client.CallOption) (*CHelloResponse, error)
}

type s3Service struct {
	c           client.Client
	serviceName string
}

func S3ServiceClient(serviceName string, c client.Client) S3Service {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "s3"
	}
	return &s3Service{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *s3Service) CHello(ctx context.Context, in *CHelloRequest, opts ...client.CallOption) (*CHelloResponse, error) {
	req := c.c.NewRequest(c.serviceName, "S3.CHello", in)
	out := new(CHelloResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for S3 service

type S3Handler interface {
	CHello(context.Context, *CHelloRequest, *CHelloResponse) error
}

func RegisterS3Handler(s server.Server, hdlr S3Handler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&S3{hdlr}, opts...))
}

type S3 struct {
	S3Handler
}

func (h *S3) CHello(ctx context.Context, in *CHelloRequest, out *CHelloResponse) error {
	return h.S3Handler.CHello(ctx, in, out)
}
