// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: s2.proto

/*
Package s2 is a generated protocol buffer package.

It is generated from these files:
	s2.proto

It has these top-level messages:
	BHelloRequest
	BHelloResponse
*/
package s2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for S2 service

type S2Service interface {
	BHello(ctx context.Context, in *BHelloRequest, opts ...client.CallOption) (*BHelloResponse, error)
}

type s2Service struct {
	c           client.Client
	serviceName string
}

func S2ServiceClient(serviceName string, c client.Client) S2Service {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "s2"
	}
	return &s2Service{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *s2Service) BHello(ctx context.Context, in *BHelloRequest, opts ...client.CallOption) (*BHelloResponse, error) {
	req := c.c.NewRequest(c.serviceName, "S2.BHello", in)
	out := new(BHelloResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for S2 service

type S2Handler interface {
	BHello(context.Context, *BHelloRequest, *BHelloResponse) error
}

func RegisterS2Handler(s server.Server, hdlr S2Handler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&S2{hdlr}, opts...))
}

type S2 struct {
	S2Handler
}

func (h *S2) BHello(ctx context.Context, in *BHelloRequest, out *BHelloResponse) error {
	return h.S2Handler.BHello(ctx, in, out)
}
